### ISSUE TITLE
Do not lock diskette image file.

### ISSUE THREAD

**Issue by aberranthacker** [nzeemin/ukncbtl#2]
Образ дискеты после монтирования в эмулятор блокируется на запись.
Это несколько неудобно при отлатдке - необходимо переходить в эмулятор чтобы размонтировать образ и после модификации образа вновь смонтироват его.

Очень хочется например чтобы скрипт собирающий мой проект мог бы записать перекомпилированные файлы в образ без необходимости предварительного размонтирования.

**Comment by nzeemin** [comment]
Всё правильно. Образ блокируется от записи, потому что из эмулятора он может быть изменён.
Можно сделать автоматический скрипт, который добавляет файлы в образ и запускает эмулятор с загрузкой с диска - ключ /boot, а на самом диске изменить STARTS.COM для запуска вашего SAV-файла.
Второй вариант, с более быстрой загрузкой - использовать утилиту Sav2Cartridge, которая запакует SAV-файл в BIN-образ картриджа, при загрузке выбрать загрузку с картриджа.

**Comment by aberranthacker** [comment]
Вариант с BIN-образом картриджа не подходит, т.к. в процессе работы программа подгружает данные с диска да и в 24КБ не впихнуть все(в том числе с учетом возможного сжатия).
А если добавить возможность отключать блокировку записи в настройках или опцией коммандной строки? На свой страх и риск как говориться)))

**Comment by nzeemin** [comment]
Мне совсем не хочется это включать, даже переключателем. Сейчас диск работает более-менее нормально, такая опция сильно ударяет по стабильности, а придут с испорченными данными в итоге ко мне как к автору.

**Comment by ilynxy** [comment]
Может быть разрешить вариант с shared write только для образов смонтированных в режиме read only? Тогда коллизий с одновременной записью эмулятором (он не будет ничего записывать) и внешним процессом не возникает (при условии, что эмулятор нигде не кэширует данные образа).

**Comment by aberranthacker** [comment]
Попробовал запуска эмулятора с ключем /BOOT - OS довольно долго загружается 😔
Я частенько запускаю код на реальной машинке загружаясь с HXServer. Он ничего не лочит и все изменения сразу доступны в обе стороны.И изменения образа сразу доступны в обе стороны.
Надеялся что подобное поведение несложно реаилизовать и в UKNCBTL

**Comment by aberranthacker** [comment]
По моему то что кто то может "прострелить себе ногу" совсем не повод добавлять потенциально опасную опцию (коллизии очень маловероятны)
К тому же, можно её вообще скрыть с глаз и включать вручную редактируя .ini файл или опцией коммандной строки.

**Comment by ilynxy** [comment]
@aberranth Кстати, вы можете собрать себе версию, которая не лочит файлы образов и использовать её на свой страх и риск ([нужно изменить пару строк](https://github.com/ilynxy/ukncbtl/commit/c9e0143fca98b2a2ca235cb3cfd3f259718cffbf)).

**Comment by aberranthacker** [comment]
Установить винду, вижуал студио, накатить патч и надеятся что все соберется без танцев с бубном. Сохранить образ виртуалки на случай если захочется обновить эмулятор. Да, как вариант.
Но было бы неплохо чтобы это включалось например недокументированной опции в UKNCBTL.ini

**Comment by nzeemin** [comment]
Хорошо. я понял что это для вас важно. слил к себе ветку @ilynxy и выпустил релиз. Спасибо!

**Comment by aberranthacker** [comment]
Супер! Большое спасибо :smile:
